### ISSUE TITLE
[BUG] Crash when running on a iOS 13.1 Simulator

### ISSUE THREAD

**Issue by raffaeleforgione** [fermoya/SwiftUIPager#194]
**Describe the bug**
When Running on iOS 13.1 Simulator, the app crashes becaus of the following:
dyld: Symbol not found: _$s7SwiftUI18AnimatableModifierPAAE13_makeViewList8modifier6inputs4bodyAA01_fG7OutputsVAA11_GraphValueVyxG_AA01_fG6InputsVAiA01_L0V_ANtctFZ
  Referenced from: /Users/***/Library/Developer/CoreSimulator/Devices/3BA98118-7FC5-46DA-A006-EEF202D25F2A/data/Containers/Bundle/Application/6A1A3C95-9D7C-43BD-BC81-0011FAD872F6/Spaccio Vino.app/Frameworks/SwiftUIPager.framework/SwiftUIPager
  Expected in: /System/Library/Frameworks/SwiftUI.framework/SwiftUI

**To Reproduce**
SwiftUIPager 2.0.2
Run on iOS 13.1 Simulator the following:
`
         Pager(page: page, data: pageData) { item in
                NewHomeBanner(text: item.text)
            }.onPageChanged { page in
                displayedPage = page
            }
`

**Expected behavior**
App not crashing

**Environment:**
 - OSX: iOS 13.1
 - Device: Any Simulator
- SwiftUIPager version: 2.0.2

**Comment by fermoya** [comment]
@raffaeleforgione have you tried running in a real device with iOS 13.1 installed? The error says that `AnimatableModifier` couldn't be found. If you see its declaration:
```swift
/// A modifier that can create another modifier with animation.
@available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
  public protocol AnimatableModifier : Animatable, ViewModifier {
}
```
That `protocol` should be available in iOS 13+. I've actually run the Sample project in iOS 13.1 and iOS 13.2. iOS 13.1 crashes, iOS 13.2 runs with no issue. See "Dancing With Versions" [here](https://swiftui-lab.com/swiftui-animations-part3/):
https://swiftui-lab.com/swiftui-animations-part3/

**Comment by fermoya** [comment]
[`2.1.0`](https://github.com/fermoya/SwiftUIPager/releases/tag/2.1.0) should fix this issue, although as I mentioned this seems to be an Xcode issue.

**Comment by MartinMetselaar** [comment]
This is still happening for me with 2.2.0 on iOS 13.1 and iOS 13.0

```
dyld: lazy symbol binding failed: Symbol not found: _$s7SwiftUI18AnimatableModifierPAAE13_makeViewList8modifier6inputs4bodyAA01_fG7OutputsVAA11_GraphValueVyxG_AA01_fG6InputsVAiA01_L0V_ANtctFZ
  Referenced from: ..../RPXSwiftUI.framework/RPXSwiftUI
  Expected in: /System/Library/Frameworks/SwiftUI.framework/SwiftUI
```

**Comment by fermoya** [comment]
Hi @MartinMetselaar, does this happen when you run the App or when `Pager` appears? I remember including [this](https://github.com/fermoya/SwiftUIPager/blob/1086365701cdb685820875789d14ef8602271730/Sources/SwiftUIPager/PagerContent.swift#L201) and [this](https://github.com/fermoya/SwiftUIPager/blob/1086365701cdb685820875789d14ef8602271730/Sources/SwiftUIPager/PagerContent.swift#L307) that solved this issue back then.

Could you debug and let me know please?

As I mentioned above, that error is an issue on Apple's side (the class is available in iOS 13.0) and I suspect it only happens on simulators but I couldn’t be sure

**Comment by MartinMetselaar** [comment]
It happens when the `Pager` appears and I think it is because `AnimatableModifier` is still used in [OnAnimationCompletedModifier.swift](https://github.com/fermoya/SwiftUIPager/blob/develop/Sources/SwiftUIPager/Helpers/OnAnimationCompletedModifier.swift) which is available at iOS 13.

I have downgraded the library back to 1.14.2 and submitted it to Apple for Review. When it will start releasing I can give you a definitive answer if it solved the crash.

**Comment by fermoya** [comment]
Hi @MartinMetselaar , have you tried forking the repo and changing [this line](https://github.com/fermoya/SwiftUIPager/blob/1086365701cdb685820875789d14ef8602271730/Sources/SwiftUIPager/Helpers/OnAnimationCompletedModifier.swift#L12) to:
```
@available(iOS 13.2, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
```
? I haven’t tried it yet (I will as soon as I find some time) but i think that should work

**Comment by MartinMetselaar** [comment]
Yes, I have. But that resulted also in changing the [extension](https://github.com/fermoya/SwiftUIPager/blob/1086365701cdb685820875789d14ef8602271730/Sources/SwiftUIPager/Helpers/OnAnimationCompletedModifier.swift#L42) to 13.2. But since the function [onAnimationCompleted](https://github.com/fermoya/SwiftUIPager/blob/1086365701cdb685820875789d14ef8602271730/Sources/SwiftUIPager/PagerContent.swift#L199) from the extension is used in [PagerContent](https://github.com/fermoya/SwiftUIPager/blob/1086365701cdb685820875789d14ef8602271730/Sources/SwiftUIPager/PagerContent.swift#L14) also that file needed to be changed to 13.2. Which basically makes the minimum iOS version for this framework 13.2.

**Comment by fermoyadrop** [comment]
@MartinMetselaar apologies, the change in not so direct. Can you try [this branch](https://github.com/fermoya/SwiftUIPager/tree/fix/ios13-symbol-not-found) and let me know?

**Comment by MartinMetselaar** [comment]
You branch is not working because of the following change in [OnAnimationCompletedModifier.swift](https://github.com/fermoya/SwiftUIPager/commit/590a7ee8a8e9c2e2ef4d7b8b9b95142295f55e37#diff-27a305807278ec01742b9dccf8853903df913b18b1f3899cf1e6d5d928524312)

```
- @available(iOS 13.0, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
+ @available(iOS 13.2, macOS 10.15, tvOS 13.0, watchOS 6.0, *)
```

If I revert those two lines it is working.

**Comment by fermoya** [comment]
What do you mean it’s not working? It’s not compiling? It should work because there’s [this check](https://github.com/fermoya/SwiftUIPager/blob/590a7ee8a8e9c2e2ef4d7b8b9b95142295f55e37/Sources/SwiftUIPager/PagerContent.swift#L201).

it compiles for me at least, Xcode 12.5

**Comment by MartinMetselaar** [comment]
You are right. I don't know where I made the mistake. Your branch ([fix/ios13-symbol-not-found](https://github.com/fermoya/SwiftUIPager/commit/590a7ee8a8e9c2e2ef4d7b8b9b95142295f55e37)) is working for me now.

**Comment by fermoya** [comment]
@MartinMetselaar glad to hear that. Does that mean it doesn’t crash anymore? If so, I’ll push a release ASAP

**Comment by MartinMetselaar** [comment]
It indeed does not crash anymore in the iOS 13 and 13.1 simulator. 
You don't need to rush the release for me. And, thank you for fixing it!

Were you able to reproduce the issue?

I am a little bit surprised that you weren't able to re
